name: CI
on: push
jobs:
  build:
    name: Build, lint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install dependencies for library'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: './brx-spartacus-library'
        run: npm ci
      - name: 'Build library'
        working-directory: './brx-spartacus-library'
        run: npm run build
      - name: 'Lint library'
        working-directory: './brx-spartacus-library'
        run: npm run lint
      - name: 'Test library'
        working-directory: './brx-spartacus-library'
        run: npm run test
      - name: 'Install dependencies for storefront'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: './brx-spartacus-storefront'
        run: npm ci
      - name: 'Build storefront'
        working-directory: './brx-spartacus-storefront'
        run: npm run build
      - name: 'Lint storefront'
        working-directory: './brx-spartacus-storefront'
        run: npm run lint
      - name: 'Test storefront'
        working-directory: './brx-spartacus-storefront'
        run: npm run test
