name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install dependencies for library'
        working-directory: './brx-spartacus-library'
        run: npm ci
      - name: 'Build library'
        working-directory: './brx-spartacus-library'
        run: npm run build
      - name: 'Install dependencies for storefront'
        working-directory: './brx-spartacus-storefront'
        run: npm ci
      - name: 'Build storefront'
        working-directory: './brx-spartacus-storefront'
        run: npm run build
